-- MySQL Script generated by MySQL Workbench
-- mar. 26 janv. 2016 12:00:12 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tickets
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tickets
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tickets` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `tickets` ;

-- -----------------------------------------------------
-- Table `tickets`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tickets`.`users` (
  `id_users` INT NOT NULL AUTO_INCREMENT,
  `uuid_users` VARCHAR(100) NULL,
  `name_users` VARCHAR(256) NULL,
  `first_name_users` VARCHAR(256) NULL,
  `email_users` VARCHAR(256) NULL,
  `pwd_users` VARCHAR(256) NULL,
  PRIMARY KEY (`id_users`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tickets`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tickets`.`clients` (
  `id_clients` INT NOT NULL AUTO_INCREMENT,
  `uuid_clients` VARCHAR(256) NULL,
  `nom_clients` VARCHAR(256) NULL,
  `prenom_clients` VARCHAR(256) NULL,
  `telephone_clients` VARCHAR(45) NULL,
  `email_clients` VARCHAR(256) NULL,
  `adresse_clients` VARCHAR(256) NULL,
  `cp_clients` VARCHAR(5) NULL,
  `ville_clients` VARCHAR(256) NULL,
  PRIMARY KEY (`id_clients`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tickets`.`types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tickets`.`types` (
  `id_types` INT NOT NULL AUTO_INCREMENT,
  `texte_types` VARCHAR(45) NULL,
  PRIMARY KEY (`id_types`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tickets`.`tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tickets`.`tickets` (
  `id_tickets` INT NOT NULL AUTO_INCREMENT,
  `uuid_tickets` VARCHAR(256) NULL,
  `numero_tickets` VARCHAR(45) NULL,
  `pwd_tickets` VARCHAR(256) NULL,
  `texte_tickets` VARCHAR(500) NULL,
  `type_id` INT NULL,
  `clients_id` INT NULL,
  PRIMARY KEY (`id_tickets`),
  INDEX `fk_tickets_clients_idx` (`clients_id` ASC),
  INDEX `fk_tickets_type_idx` (`type_id` ASC),
  CONSTRAINT `fk_tickets_clients`
    FOREIGN KEY (`clients_id`)
    REFERENCES `tickets`.`clients` (`id_clients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tickets_type`
    FOREIGN KEY (`type_id`)
    REFERENCES `tickets`.`types` (`id_types`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
